mili:
  version: 3.8.0
template:
  repository: 'https://github.com/Val-istar-Guo/component-template.git'
  version: 2.7.6
answers:
  ci: true
  standardVersion: true
  lint: true
  lock: false
  module: commonjs
